language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
  - composer install
addons:
  code_climate:
    repo_token: 3f42a1679ff454beb444a954cd66dc50dd04e6dea61f1e5373a1e071e4777876
after_script:
  - vendor/bin/test-reporter
script:
  - phpunit --configuration phpunit.dist.xml