language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
install:
  - composer install
addons:
  code_climate:
    repo_token: 3f42a1679ff454beb444a954cd66dc50dd04e6dea61f1e5373a1e071e4777876
before_script:
  - mkdir -p build/logs
script:
  - phpunit --configuration phpunit.dist.xml
after_script:
    - CODECLIMATE_REPO_TOKEN="3f42a1679ff454beb444a954cd66dc50dd04e6dea61f1e5373a1e071e4777876" vendor/bin/test-reporter --stdout > codeclimate.json
    - bash -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports; fi;"